---
title: "Excitement Index EDA"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
```


```{r}
cfb <- read.csv("http://www.stat.cmu.edu/cmsac/sure/materials/data/regression_projects/cfb_2019_games.csv")
head(cfb)
```

```{r}
unique(cfb$home_conference)
```

Algamation of all data transformations

```{r}
cfb$home_1sthalf <- cfb$home_1_pts + cfb$home_2_pts 
cfb$home_2ndhalf <- cfb$home_3_pts + cfb$home_4_pts

cfb$away_1sthalf <- cfb$away_1_pts + cfb$away_2_pts
cfb$away_2ndhalf <- cfb$away_3_pts + cfb$away_4_pts

cfb$margin_1sthalf <- cfb$home_1sthalf - cfb$away_1sthalf
cfb$margin_game <- cfb$home_points - cfb$away_points

cfb$comeback <- (cfb$margin_game / cfb$margin_1sthalf) < 0

cfb$overtime <- !((cfb$home_1_pts + cfb$home_2_pts + cfb$home_3_pts + cfb$home_4_pts) == cfb$home_points |
                    (cfb$away_1_pts + cfb$away_2_pts + cfb$away_3_pts + cfb$away_4_pts) == cfb$away_points)
```

Some conference data is not included in this list, such as the "Big Sky", which gave us NA values for their away conference when they played teams in this dataset. So for future reasons, we will change all teams without a conference in the "Other" category.

```{r}
for (i in 1:length(cfb$X)) {
  if (is.na(cfb$away_conference[i])) {
    cfb$away_conference[i] = "Other"
  }
}
```

All games have an excitement level besides these two games:
```{r}
cfb[is.na(cfb$excitement_index),]

cfb_ei <- cfb[-c(268,625),]
```


```{r}
ggplot(cfb_ei, aes(x = excitement_index)) +
  geom_histogram(binwidth = 1, color = "black", fill = "gold4") +
  stat_function(fun = dnorm) +
  labs(title = "Normality of Excitement Index Variable",
       x = "Excitement Index") +
  theme_bw()

ggplot(cfb_ei, aes(x = excitement_index)) +
  geom_histogram(binwidth = .5)

ggplot(cfb_ei, aes(x = excitement_index)) +
  stat_ecdf()
```


```{r}
ggplot(cfb_ei, aes(sample = excitement_index)) + 
  stat_qq(color = "gold4") + 
  stat_qq_line(color = "black") +
  labs(title = "Q-Q Plot of Excitement Index")
```


