---
title: "LinRegModeling"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
library(tidyverse)

library(purrr)

library(GGally)
library(ggcorrplot)
library(dendextend)
```

```{r}
cfb <- read.csv("http://www.stat.cmu.edu/cmsac/sure/materials/data/regression_projects/cfb_2019_games.csv")
head(cfb)
```

Algamation of all data transformations

```{r}
cfb$home_1sthalf <- cfb$home_1_pts + cfb$home_2_pts 
cfb$home_2ndhalf <- cfb$home_3_pts + cfb$home_4_pts

cfb$away_1sthalf <- cfb$away_1_pts + cfb$away_2_pts
cfb$away_2ndhalf <- cfb$away_3_pts + cfb$away_4_pts

cfb$margin_1sthalf <- cfb$home_1sthalf - cfb$away_1sthalf
cfb$margin_game <- cfb$home_points - cfb$away_points

cfb$comeback <- (cfb$margin_game / cfb$margin_1sthalf) < 0

cfb$overtime <- !((cfb$home_1_pts + cfb$home_2_pts + cfb$home_3_pts + cfb$home_4_pts) == cfb$home_points |
```


```{r}
(cfb$away_1_pts + cfb$away_2_pts + cfb$away_3_pts + cfb$away_4_pts) == cfb$away_points)
```

All games have an excitement level besides these two games:
```{r}
cfb[is.na(cfb$excitement_index),]

cfb_ei <- cfb[-c(268,625),]
```

```{r}
ggplot(cfb_ei, aes(score_difference, excitement_index)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ylim(0, 10) +
  labs(x = "Score Difference", y = "Excitement Index")
```


```{r}
summary(lm(excitement_index ~ score_difference, cfb))
```


```{r}
ggplot(cfb, aes(margin_1sthalf)) +
  geom_density() +
  ggtitle("Density of 1st Half Margins") +
  xlab("1st Half Margin")

ggplot(cfb, aes(score_difference)) +
  geom_density() +
  ggtitle("Density of Score Differences") +
  xlab("Score Difference")
```



```{r}
cfb_model <- cfb_ei %>%
  dplyr::select(excitement_index, 
                home_points,
                home_1_pts, 
                home_2_pts,
                home_3_pts,
                home_4_pts,
                away_points,
                away_1_pts,
                away_2_pts,
                away_3_pts,
                away_4_pts,
                score_difference,
                home_1sthalf,
                home_2ndhalf,
                away_1sthalf,
                away_2ndhalf,
                margin_1sthalf,
                margin_game)
cfb_cor_matrix <- cor(cfb_model)
ggcorrplot(cfb_cor_matrix)
```


```{r}
round_cor_matrix <- 
  round(cor(cfb_cor_matrix), 1)
ggcorrplot(cfb_cor_matrix, 
           hc.order = TRUE,
           type = "lower")
```

```{r}
summary(lm(excitement_index ~ home_1sthalf, cfb))$r.squared
summary(lm(excitement_index ~ away_1sthalf, cfb))$r.squared
summary(lm(excitement_index ~ margin_1sthalf, cfb))$r.squared
summary(lm(excitement_index ~ margin_game, cfb))$r.squared
```

```{r}
cfb_select_model <- cfb_ei %>%
  dplyr::select(excitement_index, 
                score_difference,
                comeback,
                home_1sthalf,
                margin_1sthalf,
                overtime,
                margin_game)
cfb_select_cor_matrix <- cor(cfb_select_model)
ggcorrplot(cfb_select_cor_matrix)
```


```{r}
round_cor_matrix <- 
  round(cor(cfb_select_cor_matrix), 2)
ggcorrplot(cfb_select_cor_matrix, 
           hc.order = TRUE,
           type = "lower",
           lab = TRUE)
```


```{r}
cfb_ex_vars <- dplyr::select(cfb_select_model, -excitement_index)
exp_cor_matrix <- cor(cfb_ex_vars)
cor_dist_matrix <- 1 - abs(exp_cor_matrix)
cor_dist_matrix <- as.dist(cor_dist_matrix)

library(ggdendro)
nfl_exp_hc <- hclust(cor_dist_matrix,
                     "complete") 
ggdendrogram(nfl_exp_hc,
             rotate = TRUE,
             size = 2)
```


```{r}
ggpairs(cfb_select_model,
        columns =
          c("excitement_index", 
                "score_difference",
                'comeback',
                'margin_1sthalf'))
```



```{r}
set.seed(2020)
cfb_select_model <- cfb_select_model %>%
  mutate(test_fold = sample(rep(1:5, length.out = n())))
```


```{r}
get_cv_preds <- function(model_formula, data = cfb_select_model) {
  # generate holdout predictions for every row based season
  map_dfr(unique(data$test_fold), 
          function(holdout) {
            # Separate test and training data:
            test_data <- data %>%
              filter(test_fold == holdout)
            train_data <- data %>%
              filter(test_fold != holdout)
            
            # Train model:
            reg_model <- lm(as.formula(model_formula), data = train_data)
            
            # Return tibble of holdout results:
            tibble(test_preds = predict(reg_model, newdata = test_data),
                   test_actual = test_data$excitement_index,
                   test_fold = holdout) 
          })
}
```


```{r}
test <- get_cv_preds("excitement_index ~ score_difference + margin_1sthalf")

test2 <- get_cv_preds("excitement_index ~ score_difference + home_1sthalf")

test3 <- get_cv_preds("excitement_index ~ score_difference * margin_1sthalf")

test4 <- get_cv_preds("excitement_index ~ score_difference * home_1sthalf")

test5 <- get_cv_preds("excitement_index ~ margin_game + margin_1sthalf")


```


```{r}
bind_rows(mutate(test, type = "Score Diff + Margin 1st Half"),
          mutate(test2, type = "Score Diff + Home 1st Half"),
          mutate(test3, type = "Score Diff * Margin 1st Half"),
          mutate(test4, type = "Score Diff * Home 1st Half"),
          mutate(test5, type = "Margin Game + Margin 1st Half")) %>%
  group_by(type) %>%
  summarize(rmse = sqrt(mean((test_actual - test_preds)^2))) %>%
  mutate(type = fct_reorder(type, rmse)) %>%
  ggplot(aes(x = type, y = rmse)) +
  geom_point() + coord_flip() + theme_bw() +
  ggtitle("RMSE Values of Score Variables Combination") +
  ylab("Root Mean Squared Error") +
  xlab("Variable Combination")
```




```{r}
all_cv_preds <- get_cv_preds("excitement_index ~ overtime + score_difference + comeback + margin_1sthalf")

all_int_cv_preds <- get_cv_preds("excitement_index ~ overtime * comeback * score_difference * margin_1sthalf")


score_int_add_overtime_preds <- get_cv_preds("excitement_index ~ overtime + 
                                       score_difference * margin_1sthalf")

score_int_add_comeback_preds <- get_cv_preds("excitement_index ~ comeback + 
                                       score_difference * margin_1sthalf")


score_int_add_booleans_preds <- get_cv_preds("excitement_index ~ overtime + comeback + 
                                      score_difference * margin_1sthalf")

scoring_only_preds <- get_cv_preds("excitement_index ~ score_difference + margin_1sthalf")
```



```{r}
bind_rows(mutate(all_cv_preds, type = "All Added"),
          mutate(all_int_cv_preds, type = "All Interacted"),
          mutate(score_int_add_overtime_preds, type = "ScoresInt + Overtime"),
          mutate(score_int_add_comeback_preds, type = "ScoresInt + Comeback"),
          mutate(score_int_add_booleans_preds, type = "ScoresInt + Booleans")) %>%
  group_by(type) %>%
  summarize(rmse = sqrt(mean((test_actual - test_preds)^2))) %>%
  mutate(type = fct_reorder(type, rmse)) %>%
  ggplot(aes(x = type, y = rmse)) +
  geom_point() + coord_flip() + theme_bw() +
  ggtitle("RMSE Values of All Variables Combination") +
  ylab("Root Mean Squared Error") +
  xlab("Variable Combination")
```


```{r}
all_lm <- lm(excitement_index ~ overtime + comeback + score_difference * margin_1sthalf, cfb_ei)
all_scale_lm <-lm(excitement_index ~ scale(conference_game) + scale(comeback) + scale(overtime) + 
             (scale(score_difference) * scale(margin_1sthalf)), cfb_ei)

summary(all_scale_lm)
```






```{r}

ggcoef(all_scale_lm,
       vline = TRUE,
       color = "gold4",
       size = 3,
       vline_color = "gold4",
       errorbar_color = "blue",
       errorbar_height = 0.5) +
  theme_bw() +
  xlab("Individual Slope Estimate") +
  ylab("Scaled Variables")

ggcoef(all_lm)
```

```{r}
cfb_ei %>%
  mutate(init_preds = predict(all_lm)) %>%
  ggplot(aes(x = excitement_index, y = init_preds)) +
  geom_point(alpha = 0.75) +
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", color = "red") +
  theme_bw() +
  labs(x = "Observed Excitement Index", y = "Predicted Excitement Index", title = "Predicted vs. Observed Excitement Index")

```

